name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3

    - name: Set up CMake
      uses: actions/setup-cmake@v4

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} .

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Run Tests
      run: |
        cd ${{github.workspace}}/build
        ctest -C ${{matrix.build_type}} --output-on-failure 