name: CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3

    - name: Install CMake (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Install CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} . --log-level=VERBOSE

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} --verbose

    - name: Run Tests
      run: |
        cd ${{github.workspace}}/build
        ctest -C ${{matrix.build_type}} --output-on-failure --parallel 4 --timeout 30

  pull_request_tests:
    if: github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Check Test Results
      run: |
        echo "All tests passed in the build job. Pull request is ready for review." 